export const SHORT_WORDS = [
  "at", "in", "it", "to", "up", "we",
  "ace", "act", "add", "age", "aid", "aim", "air", "arm", "art", "ask",
  "bad", "bag", "bar", "bat", "bay", "bed", "bet", "big", "bit", "box",
  "bug", "bus", "cap", "car", "cry", "cup", "cut", "day", "dig", "dot",
  "dry", "ear", "eat", "end", "eye", "fan", "far", "few", "fit", "fix",
  "fly", "fog", "fox", "fun", "gap", "gas", "gun", "hat", "hit", "hot",
  "ice", "ink", "jet", "job", "joy", "key", "kid", "lab", "law", "leg",
  "lid", "log", "low", "map", "mix", "mud", "net", "nod", "oil", "old",
  "orb", "out", "pad", "pan", "pen", "pin", "pit", "pot", "rad", "red",
  "rib", "rim", "rip", "rod", "row", "run", "sad", "set", "sip", "sky",
  "son", "spy", "sun", "tab", "tag", "tap", "tax", "tea", "tie", "tin",
  "tip", "top", "toy", "try", "use", "van", "war", "wax", "web", "win",
  "wit", "zip",
] as const;

export const MEDIUM_WORDS = [
  "able", "acid", "area", "army", "back", "band", "base", "beam", "bell",
  "best", "bird", "blow", "blue", "boat", "body", "bolt", "bomb", "bond",
  "boom", "burn", "call", "calm", "camp", "card", "care", "case", "cast",
  "chip", "city", "claw", "coat", "code", "cold", "core", "cost", "crew",
  "dark", "data", "dawn", "deal", "deep", "desk", "disk", "dock", "door",
  "draw", "drop", "dual", "dust", "duty", "east", "edge", "exit", "face",
  "fact", "fail", "fall", "fast", "fate", "fear", "file", "film", "find",
  "fire", "firm", "five", "flux", "ford", "form", "fort", "fuel", "gain",
  "gate", "gear", "glow", "gold", "grid", "grow", "hail", "half", "hard",
  "harm", "heat", "helm", "hope", "host", "hour", "hull", "hunt",
  "iron", "item", "jump", "keep", "kind", "lack", "land", "last", "lead",
  "lift", "line", "link", "load", "lock", "long", "loss", "mass",
  "mesh", "mine", "miss", "mode", "moon", "move", "navy", "near", "node",
  "nose", "note", "open", "pace", "pack", "page", "pair", "park", "part",
  "pass", "path", "peak", "plan", "plot", "port", "pull", "push", "race",
  "rail", "rank", "rate", "read", "ring", "risk", "road", "rock", "roll",
  "roof", "room", "rush", "safe", "scan", "seal", "seek", "self", "ship",
  "shot", "shut", "sign", "site", "size", "slow", "soft", "song", "sort",
  "spot", "star", "step", "stop", "suit", "tank", "tape", "task", "team",
  "tech", "term", "test", "text", "thin", "time", "tone", "tool", "tour",
  "town", "trip", "tune", "turn", "type", "unit", "vast", "void", "vote",
  "wait", "wake", "walk", "wall", "wave", "weak", "west", "wide", "wild",
  "wind", "wing", "wire", "wish", "wood", "word", "work", "yard", "year",
  "zone", "alloy", "array", "blast", "brace", "cargo", "chute", "clamp",
  "cloak", "comet", "craft", "crash", "drift", "drive", "flare", "fleet",
  "forge", "frame", "frost", "ghost", "glide", "grain", "graph", "hatch",
  "hover", "hyper", "index", "inner", "laser", "latch", "layer", "light",
  "lunar", "march", "metal", "orbit", "outer", "panel", "phase", "pilot",
  "pivot", "plasma", "plate", "prism", "probe", "pulse", "quark", "radar",
  "range", "relay", "ridge", "rover", "scale", "scope", "shaft", "shell",
  "shift", "shock", "sight", "solar", "spark", "stack", "steam", "steel",
  "stern", "storm", "sweep", "swift", "trace", "track", "trail",
  "vault", "vector", "venom", "vigil", "visor", "waste", "watch", "yield",
] as const;

export const LONG_WORDS = [
  "ability", "achieve", "acquire", "advance", "already", "another",
  "asteroid", "because", "believe", "between", "captain", "central",
  "century", "certain", "challenge", "character", "complete", "computer",
  "consider", "continue", "control", "creative", "culture", "current",
  "decision", "defense", "develop", "different", "difficult", "discover",
  "effective", "electric", "emergency", "everyone", "evidence", "exercise",
  "explorer", "external", "favorite", "finally", "forever", "forward",
  "freedom", "further", "galactic", "general", "generate", "greatest",
  "however", "hundred", "identify", "imagine", "improve", "include",
  "increase", "indicate", "industry", "interest", "internal", "language",
  "learning", "machine", "material", "measure", "medical", "meeting",
  "military", "million", "mission", "morning", "movement", "national",
  "natural", "network", "nothing", "nuclear", "observe", "officer",
  "operation", "original", "package", "parallel", "pattern", "peaceful",
  "personal", "physical", "planetary", "platform", "position", "positive",
  "possible", "practice", "prepare", "present", "pressure", "prevent",
  "primary", "private", "problem", "process", "produce", "product",
  "program", "progress", "project", "property", "protect", "provide",
  "purpose", "quality", "quantum", "question", "quickly", "realize",
  "receive", "recognize", "recommend", "regional", "remember", "require",
  "research", "resource", "respond", "satellite", "science", "section",
  "security", "separate", "service", "several", "similar", "situation",
  "solution", "spaceship", "specific", "standard", "station", "strategy",
  "strength", "structure", "subject", "success", "support", "surface",
  "system", "teacher", "technology", "telescope", "terminal", "through",
  "together", "tomorrow", "training", "transport", "universe", "valuable",
  "various", "vehicle", "version", "victory", "weather", "welcome",
  "without", "working", "aphelion", "thruster", "ignition", "overwatch",
  "firelock", "gunnery", "hardpoint", "lockstep", "outbound", "perihelion",
  "reentry", "starfall", "sunward", "warhead",
] as const;

export const BOSS_PHASES = [
  ["shields", "bulkhead", "coreburn"],
  ["acquire", "overwatch", "ignition"],
  ["hardpoint", "firelock", "warhead"],
  ["outbound", "reentry", "starfall"],
  ["satellite", "telescope", "aphelion"],
  ["quantum", "parallel", "perihelion"],
] as const;

export const SUPPLY_WORDS = ["hold", "aegis", "shove", "surge", "mark"] as const;
